/*==================[INCLUSIONS]=============================================*/
#include "bsp_cfg.h"
#include "bsp_btn_ble.h"
#include "nrf_sdh.h"
#include "error_handling.h"
#include "pwr_mgmt_cfg.h"

/*==================[INTERNAL DATA DEFINITION]===============================*/
static ble_advertising_t * p_advertising = NULL;
static uint16_t * p_conn_handle = NULL;

/*==================[INTERNAL FUNCTIONS DEFINITION]==========================*/
/**@brief Function for handling events from the BSP module.
 *
 * @param[in]   event   Event generated by button press.
 */
static void bsp_event_handler(bsp_event_t event)
{
    ASSERT(p_advertising != NULL);
    ASSERT(p_conn_handle != NULL);
    uint32_t err_code;
    switch (event)
    {
        case BSP_EVENT_SLEEP:
            PwrMgmtCfg_SleepMode();
            break;

        case BSP_EVENT_DISCONNECT:
            err_code = sd_ble_gap_disconnect(*p_conn_handle, BLE_HCI_REMOTE_USER_TERMINATED_CONNECTION);
            if (err_code != NRF_ERROR_INVALID_STATE)
            {
                APP_ERROR_CHECK(err_code);
            }
            break;

        case BSP_EVENT_WHITELIST_OFF:
            if (*p_conn_handle == BLE_CONN_HANDLE_INVALID)
            {
                err_code = ble_advertising_restart_without_whitelist(p_advertising);
                if (err_code != NRF_ERROR_INVALID_STATE)
                {
                    APP_ERROR_CHECK(err_code);
                }
            }
            break;

        default:
            break;
    }
}

/*==================[EXTERNAL FUNCTIONS DEFINITION]==========================*/
void BSPCfg_Init(ble_advertising_t * p_advertising_, uint16_t * p_conn_handle_){
    ASSERT(p_advertising_ != NULL);
    ASSERT(p_conn_handle_ != NULL); 
    p_advertising = p_advertising_;
    p_conn_handle = p_conn_handle_;
    
    uint32_t err_code = bsp_init(BSP_INIT_BUTTONS, bsp_event_handler);
    APP_ERROR_CHECK(err_code);
}


/**@brief Function for initializing buttons
 *
 * @param[out] p_erase_bonds  Will be true if the clear bonding button was pressed to wake the application up.
 */
void BSPCfg_ButtonsInit(bool * p_erase_bonds)
{
    bsp_event_t startup_event;
    uint32_t err_code;

    err_code = bsp_btn_ble_init(NULL, &startup_event);
    APP_ERROR_CHECK(err_code);

    *p_erase_bonds = (startup_event == BSP_EVENT_CLEAR_BONDING_DATA);
}

/*==================[END OF FILE]============================================*/